#https://github.com/brigade/scss-lint/blob/master/lib/scss_lint/linter/README.md

scss_files: 'app/assets/stylesheets/**/*.scss'

linters:
  Indentation:
    severity: warning
    width: 2

  NameFormat:
    placeholder_convention: "^[-a-z_]+$"
    mixin_convention: "^[-a-z_]+$"
  SelectorFormat:
    convention: "^[-a-z0-9_]+$"

  StringQuotes:
    style: double_quotes

  DeclarationOrder:
    enabled: false
  PropertySortOrder:
    enabled: false
  NestingDepth:
    max_depth: 4

  IdSelector:
    enabled: false
  QualifyingElement:
    enabled: true
    allow_element_with_attribute: true
    allow_element_with_class: true
    allow_element_with_id: true

  ColorKeyword:
    enabled: false
  LeadingZero:
    style: include_zero

  Shorthand:
    enabled: false
